apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1m0s
  path: ./platform/nginx-ingress-controller
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system