---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-controller
      version: '*'
  interval: 1h0s
  releaseName: nginx-ingress-controller
  targetNamespace: nginx-ingress-controller
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true